# Spring Boot Actuator /info endpoint configuration
info.app.name: Chronopolis Core

# Ingest Configuration Properties

# Ingest Cron job properties
# tokens: the rate at which to check for bags which have all tokens and can have a Token Store written
# request: the rate at which to check for bags which need their initial replications created
ingest.cron:
  tokens: 0 0/10 * * * *
  request: 0 0/10 * * * *

# Ingest AJP Settings
# enabled: flag to enable an AJP connector
# port: the port for the connector to listen on
ingest.ajp:
  enabled: false
  port: 8009

# Ingest Local FS Scan
## cron: the cron timer for running local fs scan
## enabled: flag to enable local fs scan of bags
## username: the 'creator' to check for when scanning bags
## staging.path: the path to the filesystem on disk
ingest.scan:
  cron: 0 0 * * * *
  enabled: false
  username: admin
  staging.id: -1
  staging.path: /dev/null

# Ingest Tokenizer Settings
## cron: the cron timer for running local-tokenization
## enabled: flag to enable Local tokenization of bags
## username: the 'creator' to check for when depositing bags
## staging.id: the ID of the StorageRegion to write tokens into
## staging.path: the path to the filesystem on disk
ingest.tokenizer:
  cron: 0 0 * * * *
  enabled: false
  username: admin
  staging.id: -1
  staging.path: /dev/null

# The staging area for writing Token Stores. Non-posix support not yet implemented.
## id: The id of the StorageRegion in the Ingest server
## path: The path to the filesystem on disk
chron.stage.tokens.posix.id: -1
chron.stage.tokens.posix.path: /dev/null

# Database connection
# Initialize should be kept false so that the server does not attempt to run a drop/create on the tables
spring.datasource:
  url: jdbc:postgresql://localhost/ingest
  username: postgres
  password: dbpass
  initialize: false

# Fryway database migration: disable with spring.flyway.enabled=false by default.
# For dev environment, change spring.flyway.enabled=true to automate database migration.
# For production deployment, we can manually migrate the database with the following command:
# ../mvnw -Dflyway.user=DB_USER -Dflyway.password=DB_PWD -Dflyway.url=jdbc:postgresql://DB_HOST:5432/ingest flyway:migrate
spring.flyway:
    enabled: false
    locations: classpath:db/baseline,classpath:db/migration
    # user: postgres
    # password: postgres
    # url: jdbc:postgresql://localhost:5432/ingest

# Specify the active profile for loading various services, normally production
spring.profiles.active: development
spring.pid.file: /var/run/ingest-server.pid

# debug: true
server.port: 8080

# Default logging properties
logging.level:
  org.springframework: ERROR
  org.hibernate: ERROR
  org.chronopolis: DEBUG

---
# settings for test profile
spring:
  profiles: development
logging.file: chronopolis-ingest.log

---
# settings for production profile
spring:
  profiles: production
logging.file: /var/log/chronopolis/ingest.log

